#!/usr/bin/bash
playing=$(mocp -i 2>/dev/null | sed -n 3p | awk -F ":" '{ print $NF }')
state=$(mocp -i 2>/dev/null | sed -n 1p | awk '{ print $2}')
timeleft=$(mocp -i 2>/dev/null | sed -n 8p | awk -F "TimeLeft:" '{ print $NF }')

if
	[ "$state" = PLAY ]; then
	status="▶"
elif
	[ "$state" = PAUSE ]; then
	status="⏸️"
elif
	[ "$state" = STOP ]; then
	echo "🛑 moc idling ║"
	exit
else
	echo "🎶 moc not running ║"
	exit
fi

if
	[ -z $playing ]; then
	playing=$(mocp -i | sed -n 2p | awk -F "/" '{ print $NF }')
fi

echo -e "$status $playing [⏳$timeleft] ║"
